name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: cherryred5959/soundcloud-clone-frontend:latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
      - run: npm ci
      - run: npm run build --if-present
      - run: npm test
